### ISSUE TITLE
TODO's before going public

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/python-pubsublite#35]
- [ ] Remove `cloudbuild.yaml`.
- [ ] Change default `INSTALL_LIBRARY_FROM_SOURCE` in `samples/snippets/noxfile.py` from `True` to `False`.
- [ ] Change `pubsublite-build` back to `Kokoro` in `.github/sync-repo-settings.yaml `.
